version: "3.3"

services:
  ciot-api:
    container_name: ciot-api
    build:
      context: ./ciot-api
      dockerfile: dockerfile_dev
    volumes:
      - ./ciot-api:/code
    #   - static:/static
    #   - media:/code/data
    env_file:
      - ciot-api/.env
    ports:
      - 8000:8000
