FROM python:3.11
ENV PYTHONUNBUFFERED 1

# RUN apt-get update && apt-get install -y libproj-dev gdal-bin libpq-dev libpython3-dev build-essential
RUN apt-get update && apt-get install -y gdal-bin

WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt

CMD ./entrypoint.prod.sh