# this is not the entire service account as it should already exist as a default account created by the openshift team.
# we do however need to modify it
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: system:image-puller-default-dev
    namespace: {{ .Values.license_plate }}-tools
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-puller
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.license_plate }}-dev
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: system:image-puller-default-test
    namespace: {{ .Values.license_plate }}-tools
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-puller
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.license_plate }}-test
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: system:image-puller-default-prod
    namespace: {{ .Values.license_plate }}-tools
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-puller
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.license_plate }}-prod
