app_name: ciot
license_plate: d2cb5f
replicas: 1
image_stream_tag: develop
namespace_env: dev
limits_cpu: 250m
limits_memory: 512Mi
requests_cpu: 150m
requests_memory: 512Mi
cluster: silver
dockerhost: image-registry.openshift-image-registry.svc:5000
