# This workflow will build and push a new frontend container image to Openshift Image Stream Tools
name: Frontend Build and Push (Dev)

on:
  push:
    branches: [develop]
    paths:
      - "ciot-web/**"
  workflow_dispatch:

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest
    name: web build
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: "Build frontend"
        working-directory: "./ciot-web"
        run: |
          docker build -t image-registry.apps.silver.devops.gov.bc.ca/d2cb5f-tools/ciot-web:develop .
          docker images

      # Uses the builder service account token
      - name: "Push frontend to Openshift"
        uses: docker/login-action@v2
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.SILVER_TOOLS_BUILDER_TOKEN }}

      - name: "Push image"
        run: |
          docker push image-registry.apps.silver.devops.gov.bc.ca/d2cb5f-tools/ciot-web:develop
