# This workflow will build and push a new backend container image to Openshift Image Stream Tools
name: Backend Build and Push (Dev)

on:
  push:
    branches: [develop]
    paths:
      - 'ciot-api/**'
  workflow_dispatch:

  jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
      
      - name: "Build backend"
        run: |
          docker build ciot-api -t ciot-api:latest -t image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/ciot-api:develop
          docker images
      
      - name: "Push backend to Openshift" 
        uses: docker/login-action@v3
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.OCP_REGISTRY_PASSWORD }}
      - run: |
          docker push image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/ciot-api:develop